am__append_16 = glib-unix.c

am__append_18 = gthread-posix.c

deprecated_sources = deprecated/gallocator.c                 \
                     deprecated/gcache.c                     \
                     deprecated/gcompletion.c                \
                     deprecated/grel.c                       \
                     deprecated/gthread-deprecated.c         

libglib_2_0_la_SOURCES = $(deprecated_sources)                   \
                         glib_probes.d                           \
                         garray.c                                \
                         gasyncqueue.c                           \
                         gasyncqueueprivate.h                    \
                         gatomic.c                               \
                         gbacktrace.c                            \
                         gbase64.c                               \
                         gbitlock.c                              \
                         gbookmarkfile.c                         \
                         gbsearcharray.h                         \
                         gbytes.c                                \
                         gbytes.h                                \
                         gcharset.c                              \
                         gcharsetprivate.h                       \
                         gchecksum.c                             \
                         gconvert.c                              \
                         gdataset.c                              \
                         gdatasetprivate.h                       \
                         gdate.c                                 \
                         gdatetime.c                             \
                         gdir.c                                  \
                         genviron.c                              \
                         gerror.c                                \
                         gfileutils.c                            \
                         ggettext.c                              \
                         ghash.c                                 \
                         ghmac.c                                 \
                         ghook.c                                 \
                         ghostutils.c                            \
                         giochannel.c                            \
                         gkeyfile.c                              \
                         glibintl.h                              \
                         glib_trace.h                            \
                         glib-init.h                             \
                         glib-init.c                             \
                         glib-private.h                          \
                         glib-private.c                          \
                         glist.c                                 \
                         gmain-internal.h                        \
                         gmain.c                                 \
                         gmappedfile.c                           \
                         gmarkup.c                               \
                         gmem.c                                  \
                         gmessages.c                             \
                         gmirroringtable.h                       \
                         gnode.c                                 \
                         goption.c                               \
                         gpattern.c                              \
                         gpoll.c                                 \
                         gprimes.c                               \
                         gqsort.c                                \
                         gquark.c                                \
                         gqueue.c                                \
                         grand.c                                 \
                         gregex.c                                \
                         gscanner.c                              \
                         gscripttable.h                          \
                         gsequence.c                             \
                         gshell.c                                \
                         gslice.c                                \
                         gslist.c                                \
                         gstdio.c                                \
                         gstrfuncs.c                             \
                         gstring.c                               \
                         gstringchunk.c                          \
                         gtestutils.c                            \
                         gthread.c                               \
                         gthreadprivate.h                        \
                         gthreadpool.c                           \
                         gtimer.c                                \
                         gtimezone.c                             \
                         gtranslit.c                             \
                         gtranslit-data.h                        \
                         gtrashstack.c                           \
                         gtree.c                                 \
                         guniprop.c                              \
                         gutf8.c                                 \
                         gunibreak.h                             \
                         gunibreak.c                             \
                         gunichartables.h                        \
                         gunicollate.c                           \
                         gunicomp.h                              \
                         gunidecomp.h                            \
                         gunidecomp.c                            \
                         gunicodeprivate.h                       \
                         gurifuncs.c                             \
                         gutils.c                                \
                         gvariant.h                              \
                         gvariant.c                              \
                         gvariant-core.h                         \
                         gvariant-core.c                         \
                         gvariant-internal.h                     \
                         gvariant-parser.c                       \
                         gvariant-serialiser.h                   \
                         gvariant-serialiser.c                   \
                         gvarianttypeinfo.h                      \
                         gvarianttypeinfo.c                      \
                         gvarianttype.c                          \
                         gversion.c                              \
                         gwakeup.h                               \
                         gwakeup.c                               \
                         gprintf.c                               \
                         gprintfint.h                            \
                         valgrind.h                              \
                         $(am__append_16)                        \
                         $(am__append_17)                        \
                         $(am__append_18)                        

deprecatedinclude_HEADERS = deprecated/gallocator.h                 \
                            deprecated/gcache.h                     \
                            deprecated/gcompletion.h                \
                            deprecated/gmain.h                      \
                            deprecated/grel.h                       \
                            deprecated/gthread.h                    

glibsubinclude_HEADERS = galloca.h                               \
                         garray.h                                \
                         gasyncqueue.h                           \
                         gatomic.h                               \
                         gbacktrace.h                            \
                         gbase64.h                               \
                         gbitlock.h                              \
                         gbookmarkfile.h                         \
                         gbytes.h                                \
                         gcharset.h                              \
                         gchecksum.h                             \
                         gconvert.h                              \
                         gdataset.h                              \
                         gdate.h                                 \
                         gdatetime.h                             \
                         gdir.h                                  \
                         genviron.h                              \
                         gerror.h                                \
                         gfileutils.h                            \
                         ggettext.h                              \
                         ghash.h                                 \
                         ghmac.h                                 \
                         ghook.h                                 \
                         ghostutils.h                            \
                         gi18n.h                                 \
                         gi18n-lib.h                             \
                         giochannel.h                            \
                         gkeyfile.h                              \
                         glist.h                                 \
                         gmacros.h                               \
                         gmain.h                                 \
                         gmappedfile.h                           \
                         gmarkup.h                               \
                         gmem.h                                  \
                         gmessages.h                             \
                         gnode.h                                 \
                         goption.h                               \
                         gpattern.h                              \
                         gpoll.h                                 \
                         gprimes.h                               \
                         gqsort.h                                \
                         gquark.h                                \
                         gqueue.h                                \
                         grand.h                                 \
                         gregex.h                                \
                         gscanner.h                              \
                         gsequence.h                             \
                         gshell.h                                \
                         gslice.h                                \
                         gslist.h                                \
                         gspawn.h                                \
                         gstdio.h                                \
                         gstrfuncs.h                             \
                         gtestutils.h                            \
                         gstring.h                               \
                         gstringchunk.h                          \
                         gthread.h                               \
                         gthreadpool.h                           \
                         gtimer.h                                \
                         gtimezone.h                             \
                         gtrashstack.h                           \
                         gtree.h                                 \
                         gtypes.h                                \
                         gunicode.h                              \
                         gurifuncs.h                             \
                         gutils.h                                \
                         gvarianttype.h                          \
                         gvariant.h                              \
                         gversion.h                              \
                         gversionmacros.h                        \
                         gwin32.h                                \
                         gprintf.h                               

