am__libgdk_3_la_SOURCES_DIST = gdkapplaunchcontextprivate.h            \
                               gdkcursorprivate.h                      \
                               gdkdevicemanagerprivate.h               \
                               gdkdeviceprivate.h                      \
                               gdkdisplaymanagerprivate.h              \
                               gdkdisplayprivate.h                     \
                               gdkdndprivate.h                         \
                               gdkframeclockidle.h                     \
                               gdkframeclockprivate.h                  \
                               gdkscreenprivate.h                      \
                               gdkinternals.h                          \
                               gdkintl.h                               \
                               gdkkeysprivate.h                        \
                               gdkvisualprivate.h                      \
                               gdkx.h                                  \
                               gdk.c                                   \
                               gdkapplaunchcontext.c                   \
                               gdkcairo.c                              \
                               gdkcolor.c                              \
                               gdkcursor.c                             \
                               gdkdeprecated.c                         \
                               gdkdevice.c                             \
                               gdkdevicemanager.c                      \
                               gdkdisplay.c                            \
                               gdkdisplaymanager.c                     \
                               gdkdnd.c                                \
                               gdkevents.c                             \
                               gdkframetimings.c                       \
                               gdkglobals.c                            \
                               gdkkeys.c                               \
                               gdkkeyuni.c                             \
                               gdkoffscreenwindow.c                    \
                               gdkframeclock.c                         \
                               gdkframeclockidle.c                     \
                               gdkpango.c                              \
                               gdkpixbuf-drawable.c                    \
                               gdkproperty.c                           \
                               gdkrectangle.c                          \
                               gdkrgba.c                               \
                               gdkscreen.c                             \
                               gdkselection.c                          \
                               gdkvisual.c                             \
                               gdkwindow.c                             \
                               gdkwindowimpl.c                         \
                               gdkenumtypes.c                          \
                               gdkmarshalers.c                         \
                               gdkmarshalers.h                         \
                               gdkkeynames.c                           

